"""create teams table

Revision ID: afb820e4592a
Revises:
Create Date: 2025-07-27 17:43:21.076736

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "afb820e4592a"  # pragma: allowlist secret
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
