"""make team state and year_founded nullable

Revision ID: dbbcd80f9627
Revises: 2af3099f35b5
Create Date: 2026-08-30 14:32:25.720573

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dbbcd80f9627"  # pragma: allowlist secret
down_revision: Union[str, None] = "2af3099f35b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("teams", "state", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("teams", "year_founded", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("teams", "year_founded", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("teams", "state", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
