# pipelines.yaml -- these dont work
pipelines:
  all-checks:
    steps:
      - api: ["all-checks"]
      - web: ["all-checks"]
      - ingestion-engine: ["all-checks"]
      - model-engine: ["all-checks"]
      - sync-engine: ["all-checks"]
      - transformation-engine: ["all-checks"]
  all-tests:
    steps:
      - api: ["integration-test"]
      - web: ["test"]
      - ingestion-engine: ["test"]
      - model-engine: ["test"]
      - sync-engine: ["test"]
      - transformation-engine: ["test"]
