version: "3"

includes:
  ingestion:
    taskfile: ./pipelines/ingestion-engine/Taskfile.yml
    dir: ./pipelines/ingestion-engine

  model:
    taskfile: ./pipelines/model-engine/Taskfile.yml
    dir: ./pipelines/model-engine

  sync:
    taskfile: ./pipelines/sync-engine/Taskfile.yml
    dir: ./pipelines/sync-engine

  transformation:
    taskfile: ./pipelines/transformation-engine/Taskfile.yml
    dir: ./pipelines/transformation-engine

  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api

  web:
    taskfile: ./web/Taskfile.yml
    dir: ./web

tasks:
  lint:
    desc: Run lint for all services
    cmds:
      - task: api:lint
      - task: sync:lint
      - task: ingestion:lint
      - task: model:lint
      - task: transformation:dbt-parse
      - task: web:lint

  typecheck:
    desc: Run typecheck for all services
    cmds:
      - task: api:typecheck
      - task: sync:typecheck
      - task: ingestion:typecheck
      - task: model:typecheck
      - task: web:typecheck

  test:
    desc: Run tests for all services
    cmds:
      - task: sync:test
      - task: ingestion:test
      - task: model:test
      - task: web:test
      - task: transformation:dbt-test

  coverage:
    desc: Run coverage for all services
    cmds:
      - task: sync:coverage
      - task: ingestion:coverage
      - task: model:coverage

  integration-test:
    desc: Run API integration test
    cmds:
      - task: api:migrate-test
      - task: transformation:build
      - task: transformation:dbt-build
      - task: sync:run-main
      - task: api:integration-test
