version: "3"

vars:
  DAGGER_SCRIPT: "infra/dagger/cli.py"
  DAGGER_RUN: "dagger run python {{.DAGGER_SCRIPT}}"
  ENV_FILE: .env.test

includes:
  ingestion:
    taskfile: ./pipelines/ingestion-engine/Taskfile.yml
    dir: ./pipelines/ingestion-engine

  model:
    taskfile: ./pipelines/model-engine/Taskfile.yml
    dir: ./pipelines/model-engine

  sync:
    taskfile: ./pipelines/sync-engine/Taskfile.yml
    dir: ./pipelines/sync-engine

  transformation:
    taskfile: ./pipelines/transformation-engine/Taskfile.yml
    dir: ./pipelines/transformation-engine

  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api

  web:
    taskfile: ./web/Taskfile.yml
    dir: ./web

tasks:
  # Dagger based pipelines for CI and cross service orchestration
  lint:
    desc: Run lint for all servies with Dagger
    cmds:
      - "{{.DAGGER_RUN}} lint-all"
  typecheck:
    desc: Run typecheck for all servies with Dagger
    cmds:
      - "{{.DAGGER_RUN}} typecheck-all"
  test:
    desc: Run tests for all servies with Dagger
    cmds:
      - "{{.DAGGER_RUN}} test-all"
  coverage:
    desc: Run coverage for all servies with Dagger
    cmds:
      - "{{.DAGGER_RUN}} coverage-all"
  integration-test:
    desc: Run API integration test with Dagger
    cmds:
      - "{{.DAGGER_RUN}} integration-test"
  ci:
    desc: Run CI with Dagger
    cmds:
      - "{{.DAGGER_RUN}} ci-all"
