version: "3"

vars:
  DAGGER_SCRIPT: "infra/dagger/run_ci_pipeline.py"
  DAGGER_RUN: "dagger run python {{.DAGGER_SCRIPT}}"

includes:
  ingestion:
    taskfile: ./pipelines/ingestion-engine/Taskfile.yml
    dir: ./pipelines/ingestion-engine

  model:
    taskfile: ./pipelines/model-engine/Taskfile.yml
    dir: ./pipelines/model-engine

  transformation:
    taskfile: ./pipelines/transformation-engine/Taskfile.yml
    dir: ./pipelines/transformation-engine

tasks:
  all-checks:
    desc: Run all checks on all services sequentially
    cmds:
      - task ingestion:all-checks
      - task model:all-checks
      - task transformation:all-checks
