transformation_engine:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: hoop-brain
      dataset: test
      threads: 4
      timeout_seconds: 300
      keyfile: /app/keys/service_account.json
