version: "3"

vars:
  SERVICE_NAME: transformation-engine
  DAGGER_SCRIPT: "../../infra/dagger/cli.py"
  DAGGER_RUN: "dagger run python {{.DAGGER_SCRIPT}}"

tasks:
  parse:
    desc: Run dbt parse to validate project structure
    cmds:
      - "{{.DAGGER_RUN}} check {{.SERVICE_NAME}} dbt-parse"

  deps:
    desc: Install dbt dependencies
    cmds:
      - "{{.DAGGER_RUN}} check {{.SERVICE_NAME}} dbt-deps"

  build:
    desc: Run dbt build (full run - models + tests)
    cmds:
      - "{{.DAGGER_RUN}} check {{.SERVICE_NAME}} dbt-build"

  test:
    desc: Run dbt test (separate from build if needed)
    cmds:
      - "{{.DAGGER_RUN}} check {{.SERVICE_NAME}} dbt-test"

  run-dbt-build:
    desc: Run job defined in services.yaml (usually same as `build`)
    cmds:
      - "{{.DAGGER_RUN}} job {{.SERVICE_NAME}} run-dbt-build"

  all-checks:
    desc: Run all checks (parse, deps, build, test) in parallel
    cmds:
      - "{{.DAGGER_RUN}} all-checks-for-service {{.SERVICE_NAME}}"

  job:
    desc: Run job — (task job -- run-dbt-build)
    cmds:
      - "{{.DAGGER_RUN}} job {{.SERVICE_NAME}} {{.CLI_ARGS}}"
