version: "3"

vars:
  SERVICE_NAME: api
  IMAGE_NAME: "{{.SERVICE_NAME}}-dev"
  DOCKER_RUN: docker run --rm -v $PWD:/app -v /app/.venv -w /app {{.IMAGE_NAME}} uv run
  ENV_FILE: .env.test

tasks:
  build:
    desc: build local docker image for api (if needed)
    cmds:
      - docker_buildkit=1 docker build -t {{.IMAGE_NAME}} .

  lint:
    desc: Run lint check for {{.SERVICE_NAME}}
    dir: ..
    cmds:
      - "{{.DOCKER_RUN}} ruff format --check ."

  typecheck:
    desc: Run typecheck for {{.SERVICE_NAME}}
    dir: ..
    cmds:
      - "{{.DOCKER_RUN}} ruff check ."

  migrate-test:
    desc: Create the test DB and run Alembic migrations for {{.SERVICE_NAME}}
    dir: ..
    cmds:
      - >-
        docker compose run --rm api bash -c "./scripts/wait-for-db.sh db psql -h db -U postgres -c 'CREATE DATABASE hoopbrain_test' || true && ./scripts/wait-for-db.sh db uv run alembic upgrade head"

  integration-test:
    desc: Run integration tests for {{.SERVICE_NAME}}
    dir: ..
    cmds:
      - docker compose run --rm api uv run pytest tests

  run-main:
    desc: Run the {{.SERVICE_NAME}} app
    dir: ..
    cmds:
      - docker compose up api

  ci:
    desc: Run CI checks for {{.SERVICE_NAME}}
    cmds:
      - task: lint
      - task: typecheck

  all-checks:
    desc: Run all CI checks for {{.SERVICE_NAME}}
    dir: ..
    cmds:
      - task lint
      - task typecheck
